---
- hosts: all
  become: true
  pre_tasks:

  - name: Installing dnf
    yum:
      name:
        - dnf
    when: ansible_distribution == "CentOS"

  - name: Update and upgrade remote CentOS server
    dnf:
      update_cache: yes
      name:  "*"
      state: latest
    when: ansible_distribution == "CentOS"

  - name: dpkg fixing in Ubuntu
    shell:
      dpkg --configure -a
    when: ansible_distribution == "Ubuntu"

  - name: Update and upgrade Ubuntu
    apt:
      update_cache: yes
      upgrade: yes
    when: ansible_distribution == "Ubuntu"

- hosts: elastic_server
  become: true
  roles:
    - elastic_search
    - kibana
    - logstash

- hosts: nagios_server
  become: true
  roles:
    - nagios_server

- hosts: prometheus_server
  become: true
  roles:
    - prometheus_server

